### ISSUE TITLE
[Help] How to get specific item from `ts-human-duration`

### ISSUE THREAD

**Issue by azzamsa** [alphapapa/ts.el#10]
I want to get specific item from `ts-human-duration` e.g year or month only. But no luck.

``` elisp
ELISP> (ts-difference current-time brith-date)
820565399.1534255

ELISP> (ts-human-format-duration (ts-difference current-time brith-date))
"26 years, 7 days, 6 hours, 49 minutes, 59 seconds"


# I want to take the year only


ELISP> (ts-format "%Y" (ts-difference current-time brith-date))
*** Eval error ***  Wrong type argument: ts, 820565399.1534255

ELISP> (ts-year (ts-human-format-duration (ts-difference current-time brith-date)))
*** Eval error ***  Wrong type argument: ts, "26 years, 7 days, 6 hours, 49
minutes, 59 seconds"

ELISP> (setq *duration* (ts-human-duration (ts-difference current-time brith-date)))
(:years 26 :days 7 :hours 6 :minutes 49 :seconds 59)

ELISP> *duration*
(:years 26 :days 7 :hours 6 :minutes 49 :seconds 59)


ELISP> (plist-get *duration* 'years)
nil

ELISP> (ts-year *duration*)
*** Eval error ***  Wrong type argument: ts, (:years 26 :days 7 :hours 6 :minutes 49 :seconds 59)

ELISP> (ts-format "%Y" *duration*)
*** Eval error ***  Wrong type argument: ts, (:years 26 :days 7 :hours 6 :minutes 49 :seconds 59)

ELISP> (type-of *duration*)
cons
```

I don't find it in [example](https://github.com/alphapapa/ts.el/blob/master/README.org#L146) nor in [test](https://github.com/alphapapa/ts.el/blob/master/test/test.el#L238)

Thank you in advance

**Comment by alphapapa** [comment]
> (plist-get *duration* 'years)

You're using the wrong symbol.

**Comment by azzamsa** [comment]
Isn't `(plist-get duration 'years)` is correct code?

I saw the code example in https://www.gnu.org/software/emacs/manual/html_node/elisp/Plist-Access.html is `(plist-get '(foo 4) 'foo)`

**Comment by alphapapa** [comment]
You need to read about keyword symbols.  You should probably read the Elisp manual.

For general Elisp help, please use an appropriate forum.

**Comment by azzamsa** [comment]
Thanks for the hint, I found it in [ts.el codebase](https://github.com/alphapapa/ts.el/blob/df48734ef046547c1aa0de0f4c07d11964ef1f7f/ts.el#L129)

``` elisp
ELISP> (plist-get *duration* :years)
25 (#o31, #x19, ?\C-y)
ELISP> (plist-get *duration* :days)
173 (#o255, #xad)
ELISP>
```

Previously I use `:years` but it comes up with other error, so I think `'years` is the correct one. So that I keep trying with it.

Thank you for ts.el

**Comment by alphapapa** [comment]
Be sure to read the Elisp manual about property lists.

Thanks.
