### ISSUE TITLE
Thanks a ton for ts

### ISSUE THREAD

**Issue by azzamsa** [alphapapa/ts.el#2]
Hi Alphapapa.

Thank you so much for ts. It's really speed up my development
time. The first time I tried in REPL. It's just WOW!.

``` elisp
ELISP> (setq mydate "Thursday, January  31, 2019")
"Thursday, January  31, 2019"
ELISP> (ts-format nil (ts-parse mydate))
"2019-01-31 00:00:00 +0700"
ELISP> (ts-parse mydate)
#s(ts nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil 1548867600.0)

ELISP> (ts-dec 'day 1 (ts-parse mydate))
#s(ts nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil 1548781200.0)

ELISP> (ts-format nil (ts-dec 'day 1 (ts-parse mydate)))
"2019-01-30 00:00:00 +0700"
ELISP> (ts-format nil (ts-inc 'day 2 (ts-parse mydate)))
"2019-02-02 00:00:00 +0700"
ELISP> (ts-format "%A, %B %e, %Y" (ts-inc 'day 2 (ts-parse mydate)))
"Saturday, February  2, 2019"
ELISP>
```

I really feel the difference than 'traditional' way. I made [my first
Emacs package](https://github.com/azzamsa/salah-time) weeks ago, some
part deal with timestamp and it just not beautiful.

``` elisp
(defun waiting-time (goal-time)
  "Return Hour and Minutes of remaining time against salah time (GOAL-TIME)."
  (let* ((curr-time (split-string (format-time-string "%H %M" (current-time))))
         (curr-hour-in-sec (* (string-to-number (nth 0 curr-time)) 3600))
         (curr-minute-in-sec (* (string-to-number (nth 1 curr-time)) 60))
         (curr-time-in-sec (+ curr-hour-in-sec curr-minute-in-sec))
         (goal-hour-in-sec (* (nth 2 (parse-time-string goal-time)) 3600))
         (goal-minute-in-sec (* (nth 1 (parse-time-string goal-time)) 60))
         (goal-in-sec (+ goal-hour-in-sec goal-minute-in-sec))
         (remaining-sec (- goal-in-sec curr-time-in-sec)))
(format-seconds "%H %M" remaining-sec)))
```

It will be much more readable and less line if I use ts. But I didn't
know ts before. [someone told me](https://www.reddit.com/r/emacs/comments/ahx1ou/my_first_package_salah_time_display_the_salah/eejv2u4)

I don't use ts in my first package cause I think it didn't involve
complex datetime things. Today I want to improve my previous
`aza-today` function. This function give me today's date if no prefix
arguments supplied, else it increments or decrements.

``` elisp
(defun aza-today ()
  "Insert date according to given argument.
If no argument is given, insert today's date"
  (interactive)
  (insert
   (format-time-string "%A, %B %e, %Y"
                       (if current-prefix-arg
                           (time-add (current-time) (* (* 24 3600)
                                                       current-prefix-arg))
                         (current-time)))))
```

Today I want to improve it, so it can make thing under point as
today's date. Cause I work in org file that had this format.

![2019-02-07-08 48 01](https://user-images.githubusercontent.com/17734314/52385889-37cb5e00-2ab6-11e9-9f8e-3c36a9a0b599.png)

It's easy to add previous and next date if I input them regularly, but
it will become painful if I don't input it for days (I don't have a
time). So I have to fill the blank using copy-paste previous (not
actual today) then rename the date and day. But with [my second
version](https://github.com/azzamsa/scripts.el#insert-todays-date), it's a breeze.

``` elisp
(defun aza-today (begin end arg)
"Insert today's date.

A prefix ARG specifies how many days to move;
negative means previous day.

If region selected, parse between BEGIN and END as today's date pivot."
  (interactive "r\nP")
  (let ((date (if mark-active
                  (ts-parse (buffer-substring-no-properties begin end))
                (ts-now)))
        (arg (or arg 0)))
    (if mark-active
        (delete-region begin end))
    (insert (ts-format "%A, %B %e, %Y" (ts-adjust 'day arg date)))))
```

![aza-today](https://user-images.githubusercontent.com/17734314/52390960-a10a9b80-2acd-11e9-90c2-c15f4fcb06c8.gif)

I don't imagine if I don't use ts, this code will be hard to read and
long. Thanks lot for ts. I am extremely happy to have this library. I
hope you can push it to MELPA.

Sorry to put all of this here, I just want to deliver how ts is so
beneficial: cut my development time, easy to read, less code.

Thanks a Ton for ts

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.  I appreciate your animation showing how you're using it; that's very cool.  It's always satisfying to hear that something I made is turning out to be useful.

I haven't touched the code for a while, so maybe it's "settled" enough to submit it to MELPA soon.  I tend to think that libraries should be used and tested before being published on a larger scale, and the fact that you've done so is helpful in that regard.

BTW, in case you don't already know about them, you may find these helpful for making animations:

* https://gitlab.com/ambrevar/emacs-gif-screencast
* https://github.com/alphapapa/bashcaster

Although I suspect you might already be using `gif-screencast`.  :)

**Comment by alphapapa** [comment]
Oh, also, in case you don't know about it already, you may find Org's `datetree` capture template type useful, as it can automatically insert an item for a date in a file.  Here's some other datetree code that you might find useful: https://github.com/alphapapa/unpackaged.el#refile-to-datetree-file-using-earliestlatest-timestamp-in-entry

**Comment by azzamsa** [comment]
> Thanks for the kind words. I appreciate your animation showing how you're using it; that's very cool. It's always satisfying to hear that something I made is turning out to be useful.

Thank you :)

> so maybe it's "settled" enough to submit it to MELPA soon.

Yes, I think it's already had lot of capabilities. First I find `ts-dec` in README, then I search for it's opposite. That time I was thinking I have to wrap them so they know whenever I pass negative/positife argumenst, turn out there is `ts-adjust` which is great. I think you already thought about the corner cases.

> BTW, in case you don't already know about them, you may find these helpful for making animations:

wow those are news to me, I think I never find them in awesome-emacs, I will add them if so. Wow, this first repo bring me here to https://github.com/tarsius/keycast. You know lot of awesome rare known packages :)

for now I am using silentcast, it's suit me while for time. I thougt you are using it too, months months back, I find you commented in [their issue](https://github.com/colinkeenan/silentcast/issues/26) 

> Note: If you can think of a more concise name for this command, please send it in!

Yes, it must. I have to read the description to understand.

**Comment by mpereira** [comment]
@alphapapa thanks for writing this library!

**Comment by alphapapa** [comment]
@mpereira Thanks for the kind words.  What are you using it in?

**Comment by mpereira** [comment]
@alphapapa I used it to build an [org entry sort function based on multiple properties](https://github.com/mpereira/.emacs.d/blob/master/configuration.org#sort-org-entries-by-multiple-properties).

**Comment by alphapapa** [comment]
Cool!

**Comment by neeasade** [comment]
thanks for ts.el (and really all the org inspo you put out there, @alphapapa)

currently using ts.el with om.el to filter for scheduled items in the future (for purposes of exporting a subselection of my org file to orgzly via syncthing)

**Comment by alphapapa** [comment]
@neeasade Thanks, that would make an interesting blog post or reddit story.
