### ISSUE TITLE
Tagging 0.3?

### ISSUE THREAD

**Issue by jman-schief** [alphapapa/ts.el#30]
Hi,

I am using Doom Emacs and just downloaded this library from the latest commit on `master` using Straight.

I notice the 0.3 verison is not tagged on the git repo: is that intentional? Would that help updating downstreams (like melpa)?

Thanks for writing this library, I hope it will make working with datetimes in Emacs less unwieldly for me!

**Comment by alphapapa** [comment]
Apparently I neglected to push the git tags to GitHub when I tagged v0.3.  It doesn't make much difference in practice since MELPA doesn't use tags, and few users use MELPA Stable which does use tags (but using MELPA Stable is not generally recommended).  Anyway, I've pushed the tags now.  Thanks.
