### ISSUE TITLE
How to produce UTC timestamps?

### ISSUE THREAD

**Issue by jman-schief** [alphapapa/ts.el#31]
Hi,
I'm playing a bit with this library. In other conversations you mention that Unix timestamps are implicitedly UTC.

By looking at the API documentation I'm not 100% clear on how to produce UTC timestamps and parse them into human readable formats (I'm probably missing a mental model of how time/date are handled by Emacs).

For example my computer says:
```
$ date -u
Mon Mar 25 09:58:03 AM UTC 2024
```

How can I get the same using this library?
```
(setq-local n (ts-parse "2024-03-25 12:00:00 UTC"))
(ts-tz-abbr n) ;  => "CET"

;; how can I specify a UTC timezone?
(setq-local n2 (ts-now)) 
(ts-tz-abbr n2) ; => CET
```

thanks

**Comment by alphapapa** [comment]
Please see the docstring for `ts-parse`, which says that it calls `parse-time-string`.  Its documentation shows how to pass a time zone in the expected way.

**Comment by jman-schief** [comment]
I guess I'll follow your suggestion and look closely at the docs of `parse-time-string` and figure out an example by myself (which I could not immediately).

cheers

**Comment by alphapapa** [comment]
There are two examples in the docstring's first sentence:

```
Parse the time in STRING into (SEC MIN HOUR DAY MON YEAR DOW DST TZ).
STRING should be an ISO 8601 time string, e.g., "2020-01-15T16:12:21-08:00",
or something resembling an RFC 822 (or later) date-time, e.g.,
"Wed, 15 Jan 2020 16:12:21 -0800".
```
